//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeNote.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwesomeNote.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Hakkında.
        /// </summary>
        public static string AboutTheApp {
            get {
                return ResourceManager.GetString("AboutTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umarım programı kullanırken keyif almışsınızdır. Çünkü ben yazarken baya keyif aldım. Program hakkında taleplerinizi, bu sayfadaki İletişim butonuna tıklayarak veya direkt olarak coderserdar@outlook.com adresine mail atarak belirtirseniz ve uygulamayı oylarsanız çok sevinirim. Sizin sayenizde bu program daha çok gelişecek. İyi günler.
        /// </summary>
        public static string AboutTheAppText {
            get {
                return ResourceManager.GetString("AboutTheAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome Note Uygulaması Hakkında.
        /// </summary>
        public static string AboutTheAwesomeNote {
            get {
                return ResourceManager.GetString("AboutTheAwesomeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör Ekle.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nesne Ekle.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ekle.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Klasörleri.
        /// </summary>
        public static string AppFolder {
            get {
                return ResourceManager.GetString("AppFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome Note.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artan Sırada.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Az Dört Karakter.
        /// </summary>
        public static string AtLeastFourDigits {
            get {
                return ResourceManager.GetString("AtLeastFourDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Rengi.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Özellikleri.
        /// </summary>
        public static string BackgroundFeature {
            get {
                return ResourceManager.GetString("BackgroundFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalde kullandığım uygulamalarda görsellikten çok işlevselliğe önem veririm. Yazarken de aynı şekilde yazdım bu programı ancak herkesin benim düşündüğüm gibi düşünmediğini de bildiğim için görselliği sade olan bu programda arka plan rengini ayarlanabilir bir şekilde yaptım. Programın Genel Ayarları kısmında Arka Plan bölümünde istenirse sadece renk seçimi yaparak, istenirse de mobil cihaz içerisindeki her hangi bir fotoğrafı arka plan olarak belirleyebilmek mümkündür. Arka plan rengi uygulamanın tamamı iç [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BackgroundFeatureNote {
            get {
                return ResourceManager.GetString("BackgroundFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Resmi.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ait Olduğu Klasörün Adı.
        /// </summary>
        public static string BelongFolderName {
            get {
                return ResourceManager.GetString("BelongFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siyah.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mavi.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kahverengi.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör Değiştir.
        /// </summary>
        public static string ChangeFolder {
            get {
                return ResourceManager.GetString("ChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakter Sayısı.
        /// </summary>
        public static string CharacterNumber {
            get {
                return ResourceManager.GetString("CharacterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişime Geç.
        /// </summary>
        public static string ContactWithUs {
            get {
                return ResourceManager.GetString("ContactWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma Tarihi.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör Sil.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Klasörünüz Tüm İçeriği İle Silinecek. Onaylıyor Musunuz?.
        /// </summary>
        public static string DeleteFolderQuestion {
            get {
                return ResourceManager.GetString("DeleteFolderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notu Sil.
        /// </summary>
        public static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notu Silmek İstediğinizden Emin Misiniz?.
        /// </summary>
        public static string DeleteNoteQuestion {
            get {
                return ResourceManager.GetString("DeleteNoteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azalan Sırada.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Not Klasörünün Adını Yazınız.
        /// </summary>
        public static string EnterFolderName {
            get {
                return ResourceManager.GetString("EnterFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Notun Adını Giriniz.
        /// </summary>
        public static string EnterNoteName {
            get {
                return ResourceManager.GetString("EnterNoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Girme.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamadan Çık.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamadan Çıkmak İstediğinizden Emin Misiniz?.
        /// </summary>
        public static string ExitAppQuestion {
            get {
                return ResourceManager.GetString("ExitAppQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu İsimde Bir Klasör Zaten Mevcut.
        /// </summary>
        public static string FolderExists {
            get {
                return ResourceManager.GetString("FolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör Adı.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör Sıralama.
        /// </summary>
        public static string FolderOrder {
            get {
                return ResourceManager.GetString("FolderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör Ayarları.
        /// </summary>
        public static string FolderSettings {
            get {
                return ResourceManager.GetString("FolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi Ailesi.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Özellikleri.
        /// </summary>
        public static string FontFeature {
            get {
                return ResourceManager.GetString("FontFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program üzerinde notlar ile ilgili olarak, her klasör için bir font ailesi ve font boyutu ayarlaması yapabilirsiniz. Bunu seçtiğiniz not klasörü içerisinde Klasör Ayarları butonuna bastıktan sonra çıkan ekranda Font bölümüne gelerek yapabilirsiniz. Ekranda o an aktif olarak seçtiğiniz font ailesi ve font boyutu görünecektir. Eğer siz seçmezseniz program font ayarını otomatik olaraak Verdana ve 26 punto olarak ayarlayacaktır..
        /// </summary>
        public static string FontFeatureNote {
            get {
                return ResourceManager.GetString("FontFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi Boyutu.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dört Karakter.
        /// </summary>
        public static string FourDigits {
            get {
                return ResourceManager.GetString("FourDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Ayarlar.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almanca.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gri.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeşil.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        public static string Irish {
            get {
                return ResourceManager.GetString("Irish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi Kalın Olsun.
        /// </summary>
        public static string IsBold {
            get {
                return ResourceManager.GetString("IsBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi İtalik Olsun.
        /// </summary>
        public static string IsItalic {
            get {
                return ResourceManager.GetString("IsItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Özellikleri.
        /// </summary>
        public static string LanguageFeature {
            get {
                return ResourceManager.GetString("LanguageFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program İngilizce, Türkçe, Almanca, İspanyolca, İtalyanca, Fransızca, Portekizce, Çince, Rusça, Arapça, Farsça gibi dillere tamamen destek vermektedir. Yani uygulamada dil gerekebilecek bütün menülerde ve sayfalarda kendi dilinizi görebileceksiniz..
        /// </summary>
        public static string LanguageFeatureNote {
            get {
                return ResourceManager.GetString("LanguageFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarların etkili olması için uygulamayı baştan başlatmanız gerekebilir....
        /// </summary>
        public static string LanguageWarning {
            get {
                return ResourceManager.GetString("LanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlan.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştirilme Tarihi.
        /// </summary>
        public static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki Not.
        /// </summary>
        public static string NextNote {
            get {
                return ResourceManager.GetString("NextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu İsimde Bir Not Zaten Mevcut.
        /// </summary>
        public static string NoteExists {
            get {
                return ResourceManager.GetString("NoteExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Özellikleri.
        /// </summary>
        public static string NoteFeature {
            get {
                return ResourceManager.GetString("NoteFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not içerisinde notun adı, içinde bulunduğu klasörün adı, notun oluşturulma tarihi ve notun kendisi bulunmaktadır. Not içerisinde klasördeki bir önceki nota ve bir sonraki nota gidebilmek mümkündür. Notun adına tıklandığı zaman notun adını değiştirme mümkündür. Not metninin tamamını seçebilmek, not hakkında detaylı bilgileri görüntülemek mümkündür. Seçilen bir notu SMS veya E-Posta yoluyla gönderebilmek de mümkündür. Notu silmek veya ait olduğu klasörü değiştirebilmek de mümkündür..
        /// </summary>
        public static string NoteFeatureNote {
            get {
                return ResourceManager.GetString("NoteFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Klasörü Özellikleri.
        /// </summary>
        public static string NoteFolderFeature {
            get {
                return ResourceManager.GetString("NoteFolderFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not klasörü içerisinde, içindeki notların listesi bulunmaktadır. Buradan klasör içerisindeki her hangi bir nota gidebilmek mümkündür. Not klasörünü silebilmek mümkündür, ancak bu işlemi gerçekleştirdiğiniz zaman not klasörünü içerisindeki bütün notlarla birlikte silecektir. Bu yüzden klasör silmeden önce Senkronizasyon yaparak notlarınızı yedeklemeniz önemle tavsiye edilir. Klasöre yeni bir not ekleyebilir veya ayarlarını değiştirebilirsiniz. Ayrıca klasör adına tıkladığınız zaman klasörün adını değiştirebi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NoteFolderFeatureNote {
            get {
                return ResourceManager.GetString("NoteFolderFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Hakkında.
        /// </summary>
        public static string NoteInfo {
            get {
                return ResourceManager.GetString("NoteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Listesi.
        /// </summary>
        public static string NoteListOf {
            get {
                return ResourceManager.GetString("NoteListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Adı.
        /// </summary>
        public static string NoteName {
            get {
                return ResourceManager.GetString("NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Sıralama.
        /// </summary>
        public static string NoteOrder {
            get {
                return ResourceManager.GetString("NoteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Kaydedildi.
        /// </summary>
        public static string NoteSaved {
            get {
                return ResourceManager.GetString("NoteSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Drive.
        /// </summary>
        public static string OneDrive {
            get {
                return ResourceManager.GetString("OneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive Senkronizasyonu Tamamlandı.
        /// </summary>
        public static string OneDriveSyncCompleted {
            get {
                return ResourceManager.GetString("OneDriveSyncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turuncu.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama Özellikleri.
        /// </summary>
        public static string OrderFeature {
            get {
                return ResourceManager.GetString("OrderFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program üzerinde hem not klasörlerini hem de klasör içerisindeki notları sıralamak mümkündür. Notları ve not klasörlerini; adına, oluşturulma tarihine göre ve en son değiştirilme tarihine göre artan ve azalan şekilde sıralamak mümkündür. Not klasörlerinin sıralama ayarlarını değiştirmek için Genel Ayarlar kısmında Diğer Ayarlar bölümüne, klasör içerisindeki notların sıralama ayarlarını değiştirmek için ise Klasör Ayarları kısmındaki Diğer Ayarlar bölümüne girmek gerekmektedir. Ekranda hali hazırda seçilen a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderFeatureNote {
            get {
                return ResourceManager.GetString("OrderFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama Türü.
        /// </summary>
        public static string OrderStyle {
            get {
                return ResourceManager.GetString("OrderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Ayarlar.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif.
        /// </summary>
        public static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Yanlış.
        /// </summary>
        public static string PasswordFalse {
            get {
                return ResourceManager.GetString("PasswordFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Özelliği.
        /// </summary>
        public static string PasswordFeature {
            get {
                return ResourceManager.GetString("PasswordFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen her hangi bir not klasöründe Klasör Ayarları bölümünde Şifre kısmında o not klasörüne şifre ataması yapabilmek mümkündür. Aynı bölümden mevcut şifre de kaldırılabilir. Girilen şifre de en az 4 karakterli olmalıdır. Sadece rakam olmalı gibi bir kısıtlama söz konusu değildir. Şifre ataması yapıldıktan sonra klasöre her girişte mevcut şifreyi soracaktır. Şifre girilirken kutucuklara şifre girildikten sonra Enter tuşuna basılması yeterlidir. Bu özellik Windows Phone marketinde ilk kez bu uygulamada bulu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PasswordFeatureNote {
            get {
                return ResourceManager.GetString("PasswordFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Koruması.
        /// </summary>
        public static string PasswordProtection {
            get {
                return ResourceManager.GetString("PasswordProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Durumu.
        /// </summary>
        public static string PasswordState {
            get {
                return ResourceManager.GetString("PasswordState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Doğru.
        /// </summary>
        public static string PasswordTrue {
            get {
                return ResourceManager.GetString("PasswordTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Giriniz.
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Tekrar Giriniz.
        /// </summary>
        public static string PleaseReEnterPassword {
            get {
                return ResourceManager.GetString("PleaseReEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki Not.
        /// </summary>
        public static string PreviousNote {
            get {
                return ResourceManager.GetString("PreviousNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programın Özellikleri.
        /// </summary>
        public static string ProgramFeatures {
            get {
                return ResourceManager.GetString("ProgramFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu program ile not klasörü oluşturma, klasöre şifre atama, uygulamanın arka plan rengini değiştirme veya arka plana telefon üzerindeki fotoğraflardan birini yerleştirebilme, not klasörünün arka plan fotoğrafını değiştirebilme, içerik sorgulaması yapabilme, OneDrive senkronizasyonu, herhangi bir notun ait olduğu klasörü kolaylıkla değiştirme, tutulan notları SMS veya E-Posta yoluyla gönderme, detaylı font ve sıralama ayarları, çoklu dil desteği, not hakkında istatistiki bilgi gibi pek çok özellik bulunmaktad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProgramFeaturesNote {
            get {
                return ResourceManager.GetString("ProgramFeaturesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mor.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değerlendir.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kırmızı.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Resmini Kaldır.
        /// </summary>
        public static string RemoveBackgroundImage {
            get {
                return ResourceManager.GetString("RemoveBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarları Sıfırla.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr-TR.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanskritçe.
        /// </summary>
        public static string Sanskrit {
            get {
                return ResourceManager.GetString("Sanskrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Tamamlandı.
        /// </summary>
        public static string SearchCompleted {
            get {
                return ResourceManager.GetString("SearchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Özellikleri.
        /// </summary>
        public static string SearchFeature {
            get {
                return ResourceManager.GetString("SearchFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programda notun adı ve notun içeriği üzerinden sorgulama yapmaya imkan sağlayan bir özellik bulunmaktadır. Bu özellik sayesinde notlarınızın içinde kaybolmaktan kurtulmuş olursunuz. Sorgulama için arama yapacağınız metni yazdıktan sonra Enter tuşuna basmanız yeterli olacaktır. Sorgu sonuçları yine aynı sayfada yer alacaktır. Burada önemli bir nokta ise, eğer sorgu sonuçları içerisinde daha önceden şifrelediğiniz bir not klasörü içerisindeki nota erişmeye kalkarsanız sorgulama ekranından şifre giriş ekranına [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SearchFeatureNote {
            get {
                return ResourceManager.GetString("SearchFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Sonuçları.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama Alanını Doldurmak Zorundasınız..
        /// </summary>
        public static string SearchTrimFault {
            get {
                return ResourceManager.GetString("SearchTrimFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Seç.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Rengi Seçiniz.
        /// </summary>
        public static string SelectBackgroundColor {
            get {
                return ResourceManager.GetString("SelectBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi Ailesi Seçiniz.
        /// </summary>
        public static string SelectFontFamily {
            get {
                return ResourceManager.GetString("SelectFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi Boyu Seçiniz.
        /// </summary>
        public static string SelectFontSize {
            get {
                return ResourceManager.GetString("SelectFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Dili Seçiniz.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Not Klasörünü Seçiniz.
        /// </summary>
        public static string SelectNoteFolder {
            get {
                return ResourceManager.GetString("SelectNoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama Türü Seçiniz.
        /// </summary>
        public static string SelectOrderStyle {
            get {
                return ResourceManager.GetString("SelectOrderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama Ölçütünü Seçiniz.
        /// </summary>
        public static string SelectOrderType {
            get {
                return ResourceManager.GetString("SelectOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Durumunu Seçiniz.
        /// </summary>
        public static string SelectPasswordState {
            get {
                return ResourceManager.GetString("SelectPasswordState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome Note Uygulaması ile Gönderildi.
        /// </summary>
        public static string SendWithApp {
            get {
                return ResourceManager.GetString("SendWithApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta İle Gönder.
        /// </summary>
        public static string SendWithMail {
            get {
                return ResourceManager.GetString("SendWithMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS İle Gönder.
        /// </summary>
        public static string SendWithSMS {
            get {
                return ResourceManager.GetString("SendWithSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Ayarla.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaş.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlan.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İspanyolca.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Başarılı Bir Şekilde Oluşturuldu.
        /// </summary>
        public static string SuccessfulAddNote {
            get {
                return ResourceManager.GetString("SuccessfulAddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Klasörü Başarılı Bir Şekilde Oluşturuldu.
        /// </summary>
        public static string SuccessfulAddNoteFolder {
            get {
                return ResourceManager.GetString("SuccessfulAddNoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Rengi Başarıyla Değiştirildi.
        /// </summary>
        public static string SuccessfulBackgroundColorChanged {
            get {
                return ResourceManager.GetString("SuccessfulBackgroundColorChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Resmi Başarılı Bir Şekilde Değiştirildi.
        /// </summary>
        public static string SuccessfulBackgroundImageChanged {
            get {
                return ResourceManager.GetString("SuccessfulBackgroundImageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Resmi Başarılı Bir Şekilde Kaldırıldı.
        /// </summary>
        public static string SuccessfulBackgroundImageRemoved {
            get {
                return ResourceManager.GetString("SuccessfulBackgroundImageRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Klasör İsmi Başarılı Bir Şekilde Değiştirildi.
        /// </summary>
        public static string SuccessfulChangeFolderName {
            get {
                return ResourceManager.GetString("SuccessfulChangeFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notunuzun Ait Olduğu Klasör Değiştirildi.
        /// </summary>
        public static string SuccessfulChangeNoteFolder {
            get {
                return ResourceManager.GetString("SuccessfulChangeNoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notun İsmi Başarılı Bir Şekilde Değiştirildi.
        /// </summary>
        public static string SuccessfulChangeNoteName {
            get {
                return ResourceManager.GetString("SuccessfulChangeNoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Klasörü Başarıyla Silindi.
        /// </summary>
        public static string SuccessfulDeleteFolder {
            get {
                return ResourceManager.GetString("SuccessfulDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Başarılı Bir Şekilde Silindi.
        /// </summary>
        public static string SuccessfulDeleteNote {
            get {
                return ResourceManager.GetString("SuccessfulDeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi Ailesi Başarılı Bir Şekilde Değiştirildi.
        /// </summary>
        public static string SuccessfulFontFamilyChanged {
            get {
                return ResourceManager.GetString("SuccessfulFontFamilyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı Tipi Boyutu Başarılı Bir Şekilde Değiştirildi.
        /// </summary>
        public static string SuccessfulFontSizeChanged {
            get {
                return ResourceManager.GetString("SuccessfulFontSizeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama Türü Başarılı Bir Şekilde Değiştirildi.
        /// </summary>
        public static string SuccessfulOrderStyleChanged {
            get {
                return ResourceManager.GetString("SuccessfulOrderStyleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama Kriteri Başarılı Bir Şekilde Değiştirildi.
        /// </summary>
        public static string SuccessfulOrderTypeChanged {
            get {
                return ResourceManager.GetString("SuccessfulOrderTypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Başarılı Bir Şekilde Kaldırıldı.
        /// </summary>
        public static string SuccessfulRemovePassword {
            get {
                return ResourceManager.GetString("SuccessfulRemovePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Plan Ayarları Başarıyla Sıfırlandı.
        /// </summary>
        public static string SuccessfulResetSettings {
            get {
                return ResourceManager.GetString("SuccessfulResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Yoluyla Not Başarılı Bir Şekilde Gönderildi.
        /// </summary>
        public static string SuccessfulSendWithMail {
            get {
                return ResourceManager.GetString("SuccessfulSendWithMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Yoluyla Not Başarılı Bir Şekilde Gönderildi.
        /// </summary>
        public static string SuccessfulSendWithSMS {
            get {
                return ResourceManager.GetString("SuccessfulSendWithSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Başarılı Bir Şekilde Oluşturuldu.
        /// </summary>
        public static string SuccessfulSetPassword {
            get {
                return ResourceManager.GetString("SuccessfulSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşzamanlama.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senkronizasyon Özellikleri.
        /// </summary>
        public static string SyncFeature {
            get {
                return ResourceManager.GetString("SyncFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program vasıtasıyla tüm notlarınızı OneDrive hesabınız ile senkronize edebilirsiniz. Uygulama içerisinde Genel Ayarlar kısmında Senkronizasyon bölümüne girdikten sonra Sign In yazan butona tıklayıp, OneDrive hesabınıza giriş yapmanız gerekmektedir. Giriş esnasında sorduğu erişim iznini onaylamadığınız zaman senkronizasyon işlemini gerçekleştirmeyecektir. Sonrasında ise Senkronizasyon için gerekli butona bastığınız zaman program OneDrive hesabınız içerisinde bir klasör oluşturacak (örneğin: Awesome Note (21. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SyncFeatureNote {
            get {
                return ResourceManager.GetString("SyncFeatureNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepsini Tek Dosyada Birleştir.
        /// </summary>
        public static string SyncOnOneFile {
            get {
                return ResourceManager.GetString("SyncOnOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşzamanlanıyor....
        /// </summary>
        public static string Syncronizing {
            get {
                return ResourceManager.GetString("Syncronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemde Bir Hata Oluştu. Uygulama Sonlanacak....
        /// </summary>
        public static string SystemFault {
            get {
                return ResourceManager.GetString("SystemFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tay Dili.
        /// </summary>
        public static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programın İpuçları.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen İki Şifre Alanı Aynı Değil.
        /// </summary>
        public static string TwoFieldsNotSame {
            get {
                return ResourceManager.GetString("TwoFieldsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba. Not almayı seven bir kullanıcı olarak Bilgisayar ve Mobil cihazlarda pek çok not tutma programı kullandım. Ve faydalı olacağını düşündüğüm özellikleri birleştirip bu uygulamayı yazdım. Umarım uygulamadan memnun kalırsınız..
        /// </summary>
        public static string WelcomeNote {
            get {
                return ResourceManager.GetString("WelcomeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelime Sayısı.
        /// </summary>
        public static string WordNumber {
            get {
                return ResourceManager.GetString("WordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sarı.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
